export const galleryItems = [
  {
    id: 1,
    title: "산에서의 일몰",
    description: "산맥 위로 펼쳐지는 아름다운 일몰.",
    imageUrl:
      "https://images.unsplash.com/photo-1725064646779-73d9f86168f1?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    dateTaken: "2023-08-01",
    location: "록키 산맥, 미국",
    tags: ["일몰", "산", "자연"],
  },
  {
    id: 2,
    title: "밤의 도시 풍경",
    description: "밤이 되면 빛으로 가득 찬 도시.",
    imageUrl: "https://example.com/images/cityscape-night.jpg",
    dateTaken: "2023-06-15",
    location: "뉴욕, 미국",
    tags: ["도시 풍경", "밤", "도시"],
  },
  {
    id: 3,
    title: "고요한 해변",
    description: "잔잔한 파도가 해변에 부드럽게 밀려오는 모습.",
    imageUrl: "https://example.com/images/serene-beach.jpg",
    dateTaken: "2023-07-10",
    location: "몰디브",
    tags: ["해변", "바다", "휴식"],
  },
  {
    id: 4,
    title: "숲길",
    description: "울창한 숲 속의 평화로운 산책로.",
    imageUrl: "https://example.com/images/forest-trail.jpg",
    dateTaken: "2023-09-05",
    location: "검은 숲, 독일",
    tags: ["숲", "산책로", "하이킹"],
  },
  {
    id: 5,
    title: "오로라",
    description: "하늘에서 춤추는 북극광.",
    imageUrl: "https://example.com/images/aurora-borealis.jpg",
    dateTaken: "2023-01-20",
    location: "트롬쇠, 노르웨이",
    tags: ["오로라", "북극광", "자연"],
  },
  {
    id: 6,
    title: "사막의 모래언덕",
    description: "맑은 하늘 아래 황금빛 모래 언덕.",
    imageUrl: "https://example.com/images/desert-dunes.jpg",
    dateTaken: "2023-03-18",
    location: "사하라 사막, 아프리카",
    tags: ["사막", "모래언덕", "모래"],
  },
  {
    id: 7,
    title: "열대 폭포",
    description: "맑은 물이 흐르는 폭포.",
    imageUrl: "https://example.com/images/tropical-waterfall.jpg",
    dateTaken: "2023-05-22",
    location: "발리, 인도네시아",
    tags: ["폭포", "열대", "자연"],
  },
  {
    id: 8,
    title: "가을 숲",
    description: "완전한 가을 색으로 물든 나무들과 땅에 떨어진 잎들.",
    imageUrl: "https://example.com/images/autumn-forest.jpg",
    dateTaken: "2023-10-11",
    location: "버몬트, 미국",
    tags: ["가을", "숲", "단풍"],
  },
  {
    id: 9,
    title: "눈 덮인 산봉우리",
    description: "맑은 하늘 아래 눈 덮인 산봉우리.",
    imageUrl: "https://example.com/images/snowy-mountain.jpg",
    dateTaken: "2023-12-01",
    location: "알프스, 스위스",
    tags: ["눈", "산", "겨울"],
  },
  {
    id: 10,
    title: "푸르른 계곡",
    description: "높은 절벽으로 둘러싸인 푸르른 계곡.",
    imageUrl: "https://example.com/images/green-valley.jpg",
    dateTaken: "2023-04-08",
    location: "요세미티, 미국",
    tags: ["계곡", "초록", "자연"],
  },
];
