const galleryItems = [
  {
    id: 1,
    title: "Sunset in the Mountains",
    description: "A beautiful sunset over the mountain range.",
    imageUrl: "https://example.com/images/sunset-mountains.jpg",
    dateTaken: "2023-08-01",
    location: "Rocky Mountains, USA",
    tags: ["sunset", "mountains", "nature"],
  },
  {
    id: 2,
    title: "Cityscape at Night",
    description: "The city comes alive with lights at night.",
    imageUrl: "https://example.com/images/cityscape-night.jpg",
    dateTaken: "2023-06-15",
    location: "New York City, USA",
    tags: ["cityscape", "night", "urban"],
  },
  {
    id: 3,
    title: "Serene Beach",
    description: "Calm waves gently lap the shore at this serene beach.",
    imageUrl: "https://example.com/images/serene-beach.jpg",
    dateTaken: "2023-07-10",
    location: "Maldives",
    tags: ["beach", "ocean", "relaxation"],
  },
  {
    id: 4,
    title: "Forest Trail",
    description: "A peaceful trail through a dense forest.",
    imageUrl: "https://example.com/images/forest-trail.jpg",
    dateTaken: "2023-09-05",
    location: "Black Forest, Germany",
    tags: ["forest", "trail", "hiking"],
  },
  {
    id: 5,
    title: "Aurora Borealis",
    description: "The Northern Lights dancing in the sky.",
    imageUrl: "https://example.com/images/aurora-borealis.jpg",
    dateTaken: "2023-01-20",
    location: "Tromsø, Norway",
    tags: ["aurora", "northern lights", "nature"],
  },
  {
    id: 6,
    title: "Desert Dunes",
    description: "Golden sand dunes under a clear blue sky.",
    imageUrl: "https://example.com/images/desert-dunes.jpg",
    dateTaken: "2023-03-18",
    location: "Sahara Desert, Africa",
    tags: ["desert", "dunes", "sand"],
  },
  {
    id: 7,
    title: "Tropical Waterfall",
    description: "A waterfall cascading into a crystal clear pool.",
    imageUrl: "https://example.com/images/tropical-waterfall.jpg",
    dateTaken: "2023-05-22",
    location: "Bali, Indonesia",
    tags: ["waterfall", "tropical", "nature"],
  },
  {
    id: 8,
    title: "Autumn Forest",
    description: "Trees in full autumn colors with leaves on the ground.",
    imageUrl: "https://example.com/images/autumn-forest.jpg",
    dateTaken: "2023-10-11",
    location: "Vermont, USA",
    tags: ["autumn", "forest", "fall"],
  },
  {
    id: 9,
    title: "Snowy Mountain Peak",
    description: "A snow-capped mountain peak against a clear sky.",
    imageUrl: "https://example.com/images/snowy-mountain.jpg",
    dateTaken: "2023-12-01",
    location: "Alps, Switzerland",
    tags: ["snow", "mountain", "winter"],
  },
  {
    id: 10,
    title: "Lush Green Valley",
    description: "A verdant valley surrounded by towering cliffs.",
    imageUrl: "https://example.com/images/green-valley.jpg",
    dateTaken: "2023-04-08",
    location: "Yosemite, USA",
    tags: ["valley", "green", "nature"],
  },
  {
    id: 11,
    title: "City Skyline at Sunset",
    description: "The city skyline silhouetted against a stunning sunset.",
    imageUrl: "https://example.com/images/city-skyline-sunset.jpg",
    dateTaken: "2023-08-15",
    location: "San Francisco, USA",
    tags: ["city", "sunset", "skyline"],
  },
  {
    id: 12,
    title: "Quiet Lakeside",
    description: "A calm lake with mountains in the distance.",
    imageUrl: "https://example.com/images/quiet-lakeside.jpg",
    dateTaken: "2023-09-22",
    location: "Banff, Canada",
    tags: ["lake", "mountains", "serenity"],
  },
  {
    id: 13,
    title: "Blossoming Cherry Trees",
    description: "Cherry blossoms in full bloom during spring.",
    imageUrl: "https://example.com/images/cherry-blossoms.jpg",
    dateTaken: "2023-04-05",
    location: "Kyoto, Japan",
    tags: ["cherry blossoms", "spring", "flowers"],
  },
  {
    id: 14,
    title: "Vibrant Coral Reef",
    description: "Colorful coral reef teeming with marine life.",
    imageUrl: "https://example.com/images/coral-reef.jpg",
    dateTaken: "2023-07-19",
    location: "Great Barrier Reef, Australia",
    tags: ["coral", "reef", "ocean"],
  },
  {
    id: 15,
    title: "Misty Morning Field",
    description: "A field covered in morning mist with the sun rising.",
    imageUrl: "https://example.com/images/misty-field.jpg",
    dateTaken: "2023-05-02",
    location: "Cotswolds, England",
    tags: ["mist", "morning", "field"],
  },
  {
    id: 16,
    title: "Starry Night Sky",
    description: "A sky full of stars over a quiet countryside.",
    imageUrl: "https://example.com/images/starry-sky.jpg",
    dateTaken: "2023-09-14",
    location: "Atacama Desert, Chile",
    tags: ["stars", "night", "astronomy"],
  },
  {
    id: 17,
    title: "Golden Wheat Field",
    description: "A golden wheat field swaying in the wind.",
    imageUrl: "https://example.com/images/wheat-field.jpg",
    dateTaken: "2023-06-20",
    location: "Tuscany, Italy",
    tags: ["wheat", "field", "golden"],
  },
  {
    id: 18,
    title: "Frozen Lake",
    description: "A lake frozen over with a layer of snow.",
    imageUrl: "https://example.com/images/frozen-lake.jpg",
    dateTaken: "2023-12-10",
    location: "Lake Baikal, Russia",
    tags: ["frozen", "lake", "winter"],
  },
  {
    id: 19,
    title: "Urban Street Art",
    description: "Colorful street art on the side of a building.",
    imageUrl: "https://example.com/images/street-art.jpg",
    dateTaken: "2023-08-08",
    location: "Berlin, Germany",
    tags: ["street art", "urban", "graffiti"],
  },
  {
    id: 20,
    title: "Spring Meadow",
    description: "A meadow full of blooming flowers in spring.",
    imageUrl: "https://example.com/images/spring-meadow.jpg",
    dateTaken: "2023-04-12",
    location: "Swiss Alps, Switzerland",
    tags: ["meadow", "flowers", "spring"],
  },
];
